numero = "147"
print(numero)
print(type(numero))

numero = int(numero)
print(numero)
print(type(numero))

numero = float(numero)
print(numero)
print(type(numero))

numero = complex(numero)
print(numero)
print(type(numero))

# numero = "b" Control kc para hacerlo comentario, primero seleccionar el texto a comentar
# numero = int("numero")

bandera = 0
print(bandera)
print(type(bandera))
bandera = bool(bandera)
print(bandera)
print(type(bandera))

# numero_uno = 0 Nomenclaruta de serpiente cuando se usa guión
# numero_dos = 1

# numeroUno = 0 Nomenclatura de camello
# numeroDos = 1 

help("keywords")